package com.bond.api.enums;

public enum ClientReturnCode {
OK, CLIENT_IS_ADDED, CLIENT_ALREADY_EXIST, CLIENT_IS_DELETED, 
CLIENT_DOESNT_EXIST, WRONG_LOGIN_OR_PASSWORD, NO_RECORDS, RECORD_IS_ADDED,
RECORD_ALREADY_EXIST, RECORD_IS_DELETED, VOTE_WAS_ACCEPTED

}
