package com.bond.api.enums;

public enum ProviderReturnCode {
	OK, PROVIDER_ALREADY_EXISTS, PROVIDER_DOESNT_EXIST, 
	PROVIDER_IS_ADDED, INVALID_DATA, PROVIDER_IS_DELETED, 
	WRONG_LOGIN_OR_PASSWORD, PATTERN_WAS_CREATED, 
	PATTERN_WAS_DELETED, PATTERN_DOESNT_STILL_CREATED
}
